version: '3.8'

services:
  # Local RTMP relay for decoupling source from publishing
  mediamtx:
    image: aler9/mediamtx:latest
    container_name: rtmp-relay
    ports:
      - "1935:1935"   # RTMP
      - "8888:8888"   # HLS
      - "9997:9997"   # API
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
      - ./cache/recordings:/recordings
      - ./cache/hls:/hls
    restart: unless-stopped
    init: true

  # Enhanced streaming service with multi-process architecture
  streaming-service:
    build: .
    container_name: rtmp-streaming-service
    ports:
      - "5000:5000"
    volumes:
      - ./cache:/app/cache
      - /tmp:/tmp
    environment:
      - RTMP_URL=${RTMP_URL}
      - STREAM_KEY=${STREAM_KEY}
      - VIDEO_URL=${VIDEO_URL}
      - BACKUP_RTMP_URL=${BACKUP_RTMP_URL:-}
      - BACKUP_STREAM_KEY=${BACKUP_STREAM_KEY:-}
      - PORT=5000
      - NODE_ENV=production
      - CONTROL_KEY=${CONTROL_KEY}  # Required: Set to a secure random key for control endpoint access
      - MEDIAMTX_HOST=mediamtx
      - CACHE_DIR=/app/cache
    depends_on:
      - mediamtx
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Ensure proper signal handling for graceful shutdowns
    init: true

volumes:
  cache_data:
    driver: local