version: '3.8'

services:
  # Local RTMP relay for decoupling source from publishing
  mediamtx:
    image: aler9/mediamtx:latest
    container_name: rtmp-relay
    ports:
      - "1935:1935"   # RTMP
      - "8888:8888"   # HLS
      - "9997:9997"   # API
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
      - cache_recordings:/recordings
      - cache_hls:/hls
    networks:
      - dokploy-network
    restart: unless-stopped
    init: true
    labels:
      - "traefik.enable=false"  # Internal service, no external access needed

  # Enhanced streaming service with multi-process architecture
  streaming-service:
    build: .
    container_name: rtmp-streaming-service
    ports:
      - "5000:5000"
    volumes:
      - cache_data:/app/cache
      - /tmp:/tmp
    environment:
      - RTMP_URL=${RTMP_URL}
      - STREAM_KEY=${STREAM_KEY}
      - VIDEO_URL=${VIDEO_URL}
      - BACKUP_RTMP_URL=${BACKUP_RTMP_URL:-}
      - BACKUP_STREAM_KEY=${BACKUP_STREAM_KEY:-}
      - PORT=5000
      - NODE_ENV=production
      - CONTROL_KEY=${CONTROL_KEY}
      - MEDIAMTX_HOST=mediamtx
      - CACHE_DIR=/app/cache
    depends_on:
      - mediamtx
    networks:
      - dokploy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    init: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.streaming-service.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.streaming-service.tls=true"
      - "traefik.http.routers.streaming-service.tls.certresolver=letsencrypt"
      - "traefik.http.services.streaming-service.loadbalancer.server.port=5000"

networks:
  dokploy-network:
    external: true

volumes:
  cache_data:
    driver: local
  cache_recordings:
    driver: local  
  cache_hls:
    driver: local